import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import CuratedInquiryForm from '@/components/CuratedInquiryForm';

export const metadata: Metadata = {
  title: 'Curated Memories | UNIKMO',
  description: 'Send your photos, videos and messages. UNIKMO professionally shapes them into a finished keepsake, with an optional Times Square experience.',
  alternates: { canonical: 'https://www.unikmo.com/curated-memories' },
};

const Icon = ({ kind }: { kind: 'lock' | 'screen' | 'share' | 'upload' | 'edit' | 'card' }) => {
  const common = 'h-7 w-7';
  if (kind === 'lock') return <svg viewBox="0 0 24 24" className={common} fill="none" stroke="currentColor" strokeWidth="1.4"><rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg>;
  if (kind === 'screen') return <svg viewBox="0 0 24 24" className={common} fill="none" stroke="currentColor" strokeWidth="1.4"><path d="M3 4h18v13H3zM8 21h8M12 17v4"/></svg>;
  if (kind === 'share') return <svg viewBox="0 0 24 24" className={common} fill="none" stroke="currentColor" strokeWidth="1.4"><rect x="5" y="5" width="14" height="16" rx="2"/><path d="M12 15V3m0 0L8 7m4-4 4 4"/></svg>;
  if (kind === 'upload') return <svg viewBox="0 0 24 24" className={common} fill="none" stroke="currentColor" strokeWidth="1.4"><path d="M12 16V4m0 0L8 8m4-4 4 4M5 14v6h14v-6"/></svg>;
  if (kind === 'edit') return <svg viewBox="0 0 24 24" className={common} fill="none" stroke="currentColor" strokeWidth="1.4"><path d="m4 20 4.5-1 10-10a2.1 2.1 0 0 0-3-3l-10 10L4 20Z"/></svg>;
  return <svg viewBox="0 0 24 24" className={common} fill="none" stroke="currentColor" strokeWidth="1.4"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M7 9h5M7 13h10"/></svg>;
};

export default function CuratedMemoriesPage() {
  return <div className="min-h-screen bg-[#FCF9F4] text-[#22323A]">
    <header className="sticky top-0 z-40 border-b border-[#22323A]/[0.06] bg-[#FCF9F4]/95 backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-[1440px] items-center px-5 sm:px-8 lg:px-12"><Link href="/" aria-label="UNIKMO home"><Image src="/unikmo-logo-header.png" alt="UNIKMO — The Key to Your Memory" width={729} height={220} priority className="h-8 w-auto sm:h-9" /></Link><nav className="ml-auto hidden items-center gap-8 text-[11px] text-[#22323A]/70 md:flex"><Link href="/#how">How it works</Link><Link href="/faq">FAQ</Link></nav><a href="#start" className="ml-auto rounded-lg bg-[#B38846] px-5 py-3 text-[11px] font-medium text-white transition hover:bg-[#9D773D] md:ml-8">Start Curated</a></div></header>
    <main>
      <section className="px-5 pb-14 pt-12 text-center sm:px-8 sm:pt-16 lg:pt-20"><h1 className="mx-auto max-w-[980px] font-serif text-[37px] leading-[1.04] tracking-[-0.025em] sm:text-[52px] lg:text-[62px]">You bring the moments. We make the memory.</h1><div className="mx-auto mt-9 grid max-w-[1240px] gap-5 lg:grid-cols-2"><div className="relative aspect-[3/2] overflow-hidden rounded-[24px]"><Image src="/curated-wedding-billboard.webp" alt="A curated wedding memory displayed in Times Square" fill priority className="object-cover" sizes="(max-width:1024px) 100vw, 50vw" /></div><div className="relative aspect-[3/2] overflow-hidden rounded-[24px] border border-[#B38846]/20 bg-[radial-gradient(circle_at_50%_40%,#FFFDF9_0%,#F3EAE0_65%,#E8DDD1_100%)]"><div className="absolute inset-[10%] overflow-hidden rounded-[14px] border border-white/60 shadow-[0_24px_55px_rgba(40,30,20,.16)]"><Image src="/card-front.png" alt="Front of the finished UNIKMO card" fill className="object-cover" sizes="(max-width:1024px) 80vw, 40vw" /></div></div></div><p className="mx-auto mt-7 max-w-[820px] text-[15px] leading-[1.72] text-[#22323A]/68 sm:text-[17px]">Send us the photos, videos and messages you choose. We professionally assemble them into one finished UNIKMO memory—then you decide whether to keep it private, show it in Times Square, or share extra keepsakes.</p><div className="mt-6 flex flex-wrap items-center justify-center gap-6"><a href="#start" className="inline-flex min-h-[48px] items-center rounded-lg bg-[#B38846] px-7 text-[12px] font-medium text-white">Start Curated</a><a href="#experiences" className="text-[12px] text-[#22323A]/70 underline decoration-[#B38846]/50 underline-offset-4">See the three choices</a></div><p className="mt-5 text-[11px] text-[#22323A]/48">Curated is optional. Standard UNIKMO remains self-created and private by design.</p></section>

      <section className="px-5 pb-8 sm:px-8"><div className="mx-auto max-w-[1240px] rounded-[22px] border border-[#B38846]/25 bg-[#F8F2EB] px-6 py-10 sm:px-10"><h2 className="text-center font-serif text-[32px] sm:text-[40px]">Keep it. Show it. Share it.</h2><div className="mt-9 grid gap-8 md:grid-cols-3">{[
        ['lock','Keep It — Curated','Professionally curated into one personalized UNIKMO card.'],['screen','Show It + Keep It','Your memory on Times Square, captured and preserved inside UNIKMO.'],['share','Share It','Additional personalized physical copies for the people who matter.'],
      ].map(([kind,title,copy])=><article key={title} className="text-center md:border-r md:border-[#B38846]/20 md:last:border-r-0"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full border border-[#B38846]/45 text-[#B38846]"><Icon kind={kind as 'lock'|'screen'|'share'} /></div><h3 className="mt-5 font-serif text-[23px]">{title}</h3><p className="mx-auto mt-3 max-w-[290px] text-[13px] leading-[1.65] text-[#22323A]/62">{copy}</p></article>)}</div></div></section>

      <section className="px-5 py-14 sm:px-8 lg:py-20"><div className="mx-auto grid max-w-[1240px] items-center gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><h2 className="font-serif text-[38px] leading-[1.05] sm:text-[48px]">From wow<br/>to keepsake.</h2><div className="mt-8 flex items-center gap-3 text-[10px] uppercase tracking-[0.16em] text-[#22323A]/60"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-[#B38846] text-white">1</span><span>Pop</span><span>→</span><span className="flex h-7 w-7 items-center justify-center rounded-full bg-[#B38846] text-white">2</span><span>Public</span><span>→</span><span className="flex h-7 w-7 items-center justify-center rounded-full bg-[#B38846] text-white">3</span><span>Keep</span></div></div><div className="grid gap-4 sm:grid-cols-2"><div className="relative aspect-[3/2] overflow-hidden rounded-[20px]"><Image src="/curated-anniversary-billboard.webp" alt="Curated anniversary memory on a city billboard" fill className="object-cover" sizes="(max-width:640px) 100vw, 35vw" /></div><div className="relative aspect-[3/2] overflow-hidden rounded-[20px]"><Image src="/curated-wedding-billboard.webp" alt="Friends watching a curated wedding memory in Times Square" fill className="object-cover" sizes="(max-width:640px) 100vw, 35vw" /></div></div></div></section>

      <section className="bg-[#F8F2EB] px-5 py-14 sm:px-8 lg:py-20"><div className="mx-auto max-w-[1240px]"><h2 className="text-center font-serif text-[32px] sm:text-[40px]">How curated works</h2><div className="mt-10 grid gap-6 md:grid-cols-4">{[
        ['upload','01','Send your moments','Upload the photos, videos and messages that matter most.'],['edit','02','We create the story','Our team crafts a finished UNIKMO memory for you.'],['screen','03','Add Times Square if you want','Choose whether to feature it on a Times Square billboard.'],['card','04','Receive it digitally or physically','Keep it private, order prints, or share your memory.'],
      ].map(([kind,n,title,copy])=><article key={n} className="rounded-[18px] border border-[#B38846]/20 bg-[#FCF9F4]/70 p-6"><div className="flex items-center justify-between text-[#B38846]"><span className="flex h-12 w-12 items-center justify-center rounded-full border border-[#B38846]/40"><Icon kind={kind as 'upload'|'edit'|'screen'|'card'} /></span><span className="font-serif text-[18px] text-[#22323A]/75">{n}</span></div><h3 className="mt-5 font-serif text-[21px]">{title}</h3><p className="mt-3 text-[12px] leading-[1.65] text-[#22323A]/58">{copy}</p></article>)}</div></div></section>

      <section id="experiences" className="px-5 py-14 sm:px-8 lg:py-20"><div className="mx-auto max-w-[1100px]"><h2 className="text-center font-serif text-[32px] sm:text-[40px]">Choose your curated experience</h2><div className="mt-10 grid gap-6 md:grid-cols-3">{[
        ['Keep It — Curated','Professionally curated into one personalized UNIKMO card.','From $49','Keep It'],['Show It + Keep It','Your memory on Times Square / Nasdaq, captured and preserved inside UNIKMO.','From $99','Most popular'],['Share It','Additional personalized physical copies. $12 each; 3 additional copies = $36.','$12 each','Share It'],
      ].map(([title,copy,price,badge],i)=><article key={title} className={`relative rounded-[20px] border bg-white/50 p-7 text-center ${i===1?'border-[#B38846] shadow-[0_18px_50px_rgba(179,136,70,.10)]':'border-[#B38846]/25'}`}>{i===1?<span className="absolute left-1/2 top-0 -translate-x-1/2 -translate-y-1/2 rounded-full bg-[#B38846] px-5 py-1.5 text-[9px] font-semibold uppercase tracking-[0.15em] text-white">{badge}</span>:null}<div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full border border-[#B38846]/45 text-[#B38846]"><Icon kind={i===0?'lock':i===1?'screen':'share'} /></div><h3 className="mt-5 font-serif text-[23px]">{title}</h3><p className="mx-auto mt-3 min-h-[64px] max-w-[280px] text-[12px] leading-[1.6] text-[#22323A]/58">{copy}</p><p className="mt-5 border-t border-[#B38846]/20 pt-5 font-serif text-[22px]">{price}</p><a href="#start" className={`mt-5 inline-flex min-h-[44px] items-center rounded-lg px-6 text-[11px] font-medium ${i===1?'bg-[#B38846] text-white':'border border-[#B38846]/50 text-[#22323A]'}`}>Choose This</a></article>)}</div><p className="mt-8 text-center text-[11px] text-[#22323A]/50">A tree planted with every memory.</p></div></section>

      <section id="start" className="border-y border-[#22323A]/[0.07] bg-[#F8F2EB] px-5 py-14 text-center sm:px-8 lg:py-20"><h2 className="font-serif text-[34px] sm:text-[44px]">Ready to create a memory worth keeping?</h2><p className="mx-auto mt-4 max-w-[620px] text-[13px] leading-relaxed text-[#22323A]/60">Tell us what you’re celebrating. We’ll help you choose the right curated experience.</p><CuratedInquiryForm /></section>
    </main>
    <footer className="px-5 py-9 sm:px-8"><div className="mx-auto flex max-w-[1180px] flex-col items-center justify-between gap-5 sm:flex-row"><Image src="/unikmo-logo-header.png" alt="UNIKMO" width={729} height={220} className="h-8 w-auto"/><nav className="flex flex-wrap justify-center gap-6 text-[10px] uppercase tracking-[0.12em] text-[#22323A]/52"><Link href="/#how">How it works</Link><Link href="/faq">FAQ</Link><Link href="/">Home</Link></nav><p className="text-[10px] text-[#22323A]/45">© {new Date().getFullYear()} UNIKMO.</p></div></footer>
  </div>;
}
